### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by xeruf** [keifufu/dimland#1]
I have no experience with Nix, how do I "use the nix flake"?
It looks like this tool is exactly what I am looking for...

**Comment by keifufu** [comment]
Installing it with regular nix:
`nix profile install github:keifufu/dimland`

You can also run it without installing:
`nix run github:keifufu/dimland -- --help`

Installation instructions for nix: https://nixos.org/download/

**Comment by xeruf** [comment]
Thanks!
I simply ran `cargo build` and copied the binary into my path, that worked just as swiftly :)

**Comment by keifufu** [comment]
Yeah, nix is just another build tool in the end anyway ^^
